openapi: "3.0.0"
info:
  title: API Title
  version: "1.0.0"

servers:
  - url: http://localhost:4000/api/v1
    description: Development Server

paths:
  /products:
    post:
      summary: Create New Product
      description: Create A new Product
      responses:
        "201":
          description: Create A New Product
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Product"

components:
  schemas:
    Product:
      type: object
      required:
        - name
        - image
        - price
        - categoryId
      properties:
        name:
          type: string
        image:
          type: string
        price:
          type: number
        categoryId:
          type: string
        prescriptions:
          type: object
        description:
          type: string

  securitySchemes:
    BearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT

security:
  - BearerAuth: []
