securityDefinitions:
  jwt:
    type: apiKey
    name: authorization
    in: header

tags:
  - name: Products
    description: Products API

paths:
  /products:
    post:
      tags:
        - Products
      summary: Create Product
      # security:
      #   - jwt: []
      # parameters:
      #   - name: body
      #     in: body
      #     description: Event Data
      #     required: true
          # schema:
          #   $ref: '#/definitions/events'
      responses:
        200:
          description: 'Created'

